### ISSUE TITLE
Won’t allow hyphens in application ID

### ISSUE THREAD

**Issue by Jacalz** [ximion/metainfocreator#12]
Hi there. Thank you for creating this great piece of software. 
I was looking at using it for creating appstream metadata for my application called [wormhole-gui](https://github.com/Jacalz/wormhole-gui). When I entered the unique identifier for it (com.github.jacalz.wormhole-gui), it complained about hyphens not being allowed.

I know that  websites allow hyphens (https://wi-fi.org) and I couldn’t find any information about hyphens not being allowed for unique software identifiers (or appID). Is this something that is specific to the appstream specification or am I just missing something obvious here? I would greatly appreciate if someone could clear up the situation for me :)

**Comment by ximion** [comment]
While AppStream historically allows hyphens in component-IDs, today we try to align the component-ID with other commonly used IDs for the application, like the AppID and D-Bus interface names. The latter is especially relevant because many new apps support being launched by D-Bus (see https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#dbus ).
The benefit of having only one name is obviously to reduce confusion and needless renaming. So, while AppStream does support hyphens, D-Bus doesn't (and also no parts of the string starting with numbers). We can't remove support for hyphens from AppStream completely, as that would break backwards compatibility, but for new metadata we strongly discourage using them, and `appstreamcli validate` will throw an INFO-type hint if your component-ID contains one.
You can read more about this in the specification, see the info-box at https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic

I hope that clarifies things :-)

**Comment by ximion** [comment]
Btw, your ID could be `io.github.jacalz.wormhole_gui` or maybe `io.github.jacalz.wormholegui`. In the past, there was some debate around using the `com.github` namespace, as that would be reserved for GitHub apps themselves, while user-created stuff would be under `io.github`, but I do not recall anyone from GitHub ever weighing in on that discussion. So, using either is probably fine (the metainfo-creator will generate the .io variant regardless after entering the URL, just in case).

**Comment by Jacalz** [comment]
Thanks for taking your time with the detailed answer. It certainly does clarify things a lot. It is greatly appreciated 👍 
Yeah, you are probably right that it makes more sense to use `io.github`  over `com.github` and it makes even more sense since I am planning on creating my own `jacalz.github.io` website.

There is one issue though, [fyne](https://github.com/fyne-o/fyne) (the ui toolkit that I used for creating the application) uses the application id in it's local storage of settings and just moving over to `io.github.jacalz.wormhole_gui` would be a breaking change  as all users settings would be lost. That would warrant a 3.0.0 release, which feels a bit drastic when I recently released 2.0.0. I understand that this probably isn't something you would suggest, but would it work to create the metadata as `com.github`.jacalz.wormhole_gui` and then manually rename and modify the file as `com.github`.jacalz.wormhole-gui` until I can change the id entirely? As my software is cross-platform (thus no dbus support), it could work as a temporary solution?

**Comment by ximion** [comment]
You don't *have* to have your component-ID match all the other IDs - it's certainly nicer that way, but if doing so would result in breakage, it's better to have two separate IDs (ideally only temporarily).
So you could give your metadata an `io.github.jacalz.wormhole_gui` component-ID and just leave all other identifier as they are (you could even have a component-ID with a hyphen, but I would advise against that, just to be future-proof).

For AppStream, that ID is really only just an identification string that is used to make your app uniquely known to operating systems and software centers, and is used to associate extra data (like ratings and reviews) with it. It's not, unlike with D-Bus, used for any code generation and may differ from other IDs used in the app with the only drawback of then having in-app ID inconsistencies that may confuse the developer :-P

**Comment by Jacalz** [comment]
Alright. Thank you for the response 🙂
